CREATE TABLE "Geolocations"
(
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "Type"        integer NOT NULL DEFAULT 0,
    "Coordinates" character varying(100) NOT NULL,
    CONSTRAINT "PK_Geolocations" PRIMARY KEY ("Id")
);

CREATE TABLE "Meteorites"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId"    character varying(50)  NOT NULL,
    "Name"          character varying(255) NOT NULL,
    "NameType"      character varying(20)  NOT NULL,
    "RecClass"      character varying(50)  NOT NULL,
    "Mass"          numeric(18, 2) NULL,
    "Fall"          integer NOT NULL DEFAULT 0,
    "Year"          timestamp without time zone NULL,
    "RecLat"        numeric(10, 6) NULL,
    "RecLong"       numeric(10, 6) NULL,
    "GeolocationId" integer NULL,
    CONSTRAINT "PK_Meteorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Meteorites_Geolocations_GeolocationId" FOREIGN KEY ("GeolocationId") REFERENCES "Geolocations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Meteorites_ExternalId" ON "Meteorites" ("ExternalId");

CREATE INDEX "IX_Meteorites_Name" ON "Meteorites" ("Name");
CREATE INDEX "IX_Meteorites_RecClass" ON "Meteorites" ("RecClass");
CREATE INDEX "IX_Meteorites_Fall" ON "Meteorites" ("Fall");
CREATE INDEX "IX_Meteorites_Year" ON "Meteorites" ("Year");
CREATE INDEX "IX_Meteorites_RecLat_RecLong" ON "Meteorites" ("RecLat", "RecLong");

CREATE INDEX "IX_Geolocations_Coordinates" ON "Geolocations" ("Coordinates");

CREATE UNIQUE INDEX "IX_Meteorites_GeolocationId" ON "Meteorites" ("GeolocationId");